import type { CityDto } from '@bun-bun/shared';

export const MOLDOVA_CITIES: CityDto[] = [
  { id: 'chisinau', nameRo: 'Chișinău', nameRu: 'Кишинёв' },
  { id: 'balti', nameRo: 'Bălți', nameRu: 'Бельцы' },
  { id: 'tiraspol', nameRo: 'Tiraspol', nameRu: 'Тирасполь' },
  { id: 'bender', nameRo: 'Bender', nameRu: 'Бендеры' },
  { id: 'cahul', nameRo: 'Cahul', nameRu: 'Кагул' },
  { id: 'ungheni', nameRo: 'Ungheni', nameRu: 'Унгены' },
  { id: 'soroca', nameRo: 'Soroca', nameRu: 'Сорока' },
  { id: 'orhei', nameRo: 'Orhei', nameRu: 'Орхей' },
  { id: 'comrat', nameRo: 'Comrat', nameRu: 'Комрат' },
  { id: 'ceadir-lunga', nameRo: 'Ceadîr-Lunga', nameRu: 'Чадыр-Лунга' },
  { id: 'edinet', nameRo: 'Edineț', nameRu: 'Единец' },
  { id: 'causeni', nameRo: 'Căușeni', nameRu: 'Каушаны' },
  { id: 'straseni', nameRo: 'Strășeni', nameRu: 'Страшены' },
  { id: 'drochia', nameRo: 'Drochia', nameRu: 'Дрокия' },
  { id: 'hincesti', nameRo: 'Hîncești', nameRu: 'Хынчешты' },
  { id: 'floresti', nameRo: 'Florești', nameRu: 'Флорешты' },
  { id: 'stefan-voda', nameRo: 'Ștefan Vodă', nameRu: 'Штефан-Водэ' },
  { id: 'criuleni', nameRo: 'Criuleni', nameRu: 'Криулены' },
  { id: 'ialoveni', nameRo: 'Ialoveni', nameRu: 'Яловены' },
  { id: 'nisporeni', nameRo: 'Nisporeni', nameRu: 'Ниспорены' },
  { id: 'glodeni', nameRo: 'Glodeni', nameRu: 'Глодяны' },
  { id: 'falesti', nameRo: 'Fălești', nameRu: 'Фэлешты' },
  { id: 'singerei', nameRo: 'Sîngerei', nameRu: 'Сынжерей' },
  { id: 'rezina', nameRo: 'Rezina', nameRu: 'Резина' },
  { id: 'telenesti', nameRo: 'Telenești', nameRu: 'Теленешты' },
  { id: 'cimislia', nameRo: 'Cimișlia', nameRu: 'Чимишлия' },
  { id: 'basarabeasca', nameRo: 'Basarabeasca', nameRu: 'Басарабяска' },
  { id: 'leova', nameRo: 'Leova', nameRu: 'Леова' },
  { id: 'cantemir', nameRo: 'Cantemir', nameRu: 'Кантемир' },
  { id: 'taraclia', nameRo: 'Taraclia', nameRu: 'Тараклия' },
  { id: 'soldanesti', nameRo: 'Șoldănești', nameRu: 'Шолданешты' },
  { id: 'anenii-noi', nameRo: 'Anenii Noi', nameRu: 'Новые Анены' },
  { id: 'donduseni', nameRo: 'Dondușeni', nameRu: 'Дондюшаны' },
  { id: 'ocnita', nameRo: 'Ocnița', nameRu: 'Окница' },
  { id: 'briceni', nameRo: 'Briceni', nameRu: 'Бричаны' },
  { id: 'riscani', nameRo: 'Rîșcani', nameRu: 'Рышканы' },
  { id: 'dubasari', nameRo: 'Dubăsari', nameRu: 'Дубоссары' },
  { id: 'vulcanesti', nameRo: 'Vulcănești', nameRu: 'Вулканешты' },
  { id: 'singera', nameRo: 'Sîngera', nameRu: 'Сынжера' },
  { id: 'codru', nameRo: 'Codru', nameRu: 'Кодру' },
  { id: 'durlesti', nameRo: 'Durlești', nameRu: 'Дурлешты' },
  { id: 'vadul-lui-voda', nameRo: 'Vadul lui Vodă', nameRu: 'Вадул-луй-Водэ' },
  { id: 'cricova', nameRo: 'Cricova', nameRu: 'Крикова' },
  { id: 'calarasi', nameRo: 'Călărași', nameRu: 'Калараш' },
  { id: 'otaci', nameRo: 'Otaci', nameRu: 'Отачь' },
  { id: 'costesti', nameRo: 'Costești', nameRu: 'Костешты' },
  { id: 'lipcani', nameRo: 'Lipcani', nameRu: 'Липканы' },
  { id: 'cupcini', nameRo: 'Cupcini', nameRu: 'Купчинь' },
  { id: 'cornesti', nameRo: 'Cornești', nameRu: 'Корнешты' },
  { id: 'biruinta', nameRo: 'Biruința', nameRu: 'Бируинца' },
  { id: 'tvardita', nameRo: 'Tvardița', nameRu: 'Твардица' },
  { id: 'ghindesti', nameRo: 'Ghindești', nameRu: 'Гиндешты' },
  { id: 'iargara', nameRo: 'Iargara', nameRu: 'Яргара' },
  { id: 'rybnitsa', nameRo: 'Rîbnița', nameRu: 'Рыбница' },
  { id: 'slobozia', nameRo: 'Slobozia', nameRu: 'Слободзея' },
  { id: 'grigoriopol', nameRo: 'Grigoriopol', nameRu: 'Григориополь' },
  { id: 'camenca', nameRo: 'Camenca', nameRu: 'Каменка' },
  { id: 'dnestrovsc', nameRo: 'Dnestrovsc', nameRu: 'Днестровск' },
  { id: 'maiac', nameRo: 'Maiac', nameRu: 'Маяк' },
];
